export const TOOL_STRINGS: Record<string, { zh: string; en: string }> = {
  pdfMergeTitle: { zh: 'PDF 合并（本地）', en: 'PDF Merge (local)' },
  pdfMergeDesc: { zh: '把多个 PDF 按顺序合并成一个，100% 在浏览器内完成，不上传服务器。适合合并发票、报关单、合同。', en: 'Merge multiple PDFs in order, 100% in-browser, no upload. Great for invoices, customs docs, contracts.' },
  pdfCompressTitle: { zh: 'PDF 压缩（本地）', en: 'PDF Compress (local)' },
  pdfCompressDesc: { zh: '重新编码 PDF 以减小体积，所有处理在本地完成，文件不上传。适合压缩给买家发的目录、说明书。', en: 'Re-encode PDFs to shrink size, fully local, no upload. Good for catalogs and manuals you send to buyers.' },
  pdfSplitTitle: { zh: 'PDF 拆分（本地）', en: 'PDF Split (local)' },
  pdfSplitDesc: { zh: '按页码范围把一个 PDF 拆成多个文件，全部本地处理。例如输入 1-3,5,8-10。', en: 'Split one PDF into several by page ranges, all local. E.g. 1-3,5,8-10.' },
  imgCompressTitle: { zh: '图片压缩（本地）', en: 'Image Compress (local)' },
  imgCompressDesc: { zh: 'JPG/PNG/WebP/AVIF 本地压缩与格式转换，零上传、无水印、批量处理、ZIP 导出。适合产品图、配图优化。', en: 'JPG/PNG/WebP/AVIF compression & conversion, zero upload, no watermark, batch + ZIP. For product & web images.' },
  base64Title: { zh: 'Base64 编解码（本地）', en: 'Base64 Encode/Decode (local)' },
  base64Desc: { zh: '文本与 Base64 互转，常用于调试 API、嵌入小图标。全部本地，不上传。', en: 'Convert text ↔ Base64 for API debugging or inline icons. Fully local.' },
  vatTitle: { zh: '欧盟 VAT 计算器（本地）', en: 'EU VAT Calculator' },
  vatTitleEn: { zh: 'EU VAT Calculator', en: 'EU VAT Calculator' },
  vatDesc: { zh: '快速计算含/不含税价格与 VAT 金额，覆盖欧盟主要税率。', en: 'Quickly compute net/gross prices and VAT amount across major EU rates.' },
  pdfToImagesTitle: { zh: 'PDF 转图片（本地）', en: 'PDF to Images (local)' },
  pdfToImagesDesc: { zh: '逐页把 PDF 导出为 JPG/PNG，全部在浏览器本地完成，不上传服务器。适合把合同、说明书转成图片。', en: 'Export each PDF page as JPG/PNG, fully in-browser, no upload. Great for contracts & manuals.' },
  imgRemoveBgTitle: { zh: '图片去背景（本地）', en: 'Remove Background (local)' },
  imgRemoveBgDesc: { zh: '一键把产品图去背景成透明 PNG，模型在浏览器本地运行，零上传。', en: 'One-click transparent PNG from product photos; model runs in-browser, zero upload.' },
  imgConvertTitle: { zh: '图片格式转换（本地）', en: 'Image Convert (local)' },
  imgConvertDesc: { zh: 'JPG / PNG / WebP 互相转换，批量处理、零上传。适合统一产品图格式。', en: 'Convert JPG / PNG / WebP in batch, zero upload.' },
  imgResizeTitle: { zh: '图片缩放（本地）', en: 'Image Resize (local)' },
  imgResizeDesc: { zh: '按最长边或比例缩放产品图，批量处理、零上传。', en: 'Resize product images by max edge or ratio, batch, zero upload.' },
  imgBlindTitle: { zh: '隐形水印（本地）', en: 'Invisible Watermark (local)' },
  imgBlindDesc: { zh: '把版权指纹嵌入图片像素（肉眼不可见），事后可提取验证归属；零上传。', en: 'Embed a copyright fingerprint into pixels (invisible) and verify later; zero upload.' },
  imgWatermarkTitle: { zh: '批量水印（本地）', en: 'Batch Watermark (local)' },
  imgWatermarkDesc: { zh: '给产品图批量叠加可见版权文字，零上传。', en: 'Stamp visible copyright text on product images in batch, zero upload.' },
  jwtTitle: { zh: 'JWT 解码（本地）', en: 'JWT Decoder (local)' },
  jwtDesc: { zh: '解析店铺 API Token 的 Header / Payload，高亮过期时间，零上传。', en: 'Decode shop API token Header / Payload, highlight expiry, zero upload.' },
  pwTitle: { zh: '密码生成器（本地）', en: 'Password Generator (local)' },
  pwDesc: { zh: '用浏览器加密随机数生成强密码，零上传。', en: 'Strong passwords from crypto-random values, zero upload.' },
  jsonFmtTitle: { zh: 'JSON 格式化（本地）', en: 'JSON Formatter (local)' },
  jsonFmtDesc: { zh: '美化或压缩 JSON，零上传。', en: 'Pretty-print or minify JSON, zero upload.' },
  jsonValTitle: { zh: 'JSON 校验（本地）', en: 'JSON Validator (local)' },
  jsonValDesc: { zh: '检查 JSON 语法错误并定位行号，零上传。', en: 'Check JSON syntax and locate the error line, zero upload.' },
  jsonConvTitle: { zh: 'JSON 互转（本地）', en: 'JSON Convert (local)' },
  jsonConvDesc: { zh: 'JSON 转 CSV / YAML / XML，零上传。', en: 'JSON → CSV / YAML / XML, zero upload.' },
  profitTitle: { zh: '利润计算器（本地）', en: 'Profit Calculator (local)' },
  profitDesc: { zh: '采购 + 运费 + VAT + 平台佣金算净利润与利润率，零上传。', en: 'Net profit & margin from cost + shipping + VAT + commission, zero upload.' },
  curTitle: { zh: '货币换算（本地）', en: 'Currency Converter (local)' },
  curDesc: { zh: '多币种换算，汇率表可手动覆盖，零上传。', en: 'Multi-currency conversion with editable rates, zero upload.' },
  fbaTitle: { zh: 'FBA 费用估算（本地）', en: 'FBA Fee Estimator (local)' },
  fbaDesc: { zh: '按站点与尺寸档估算 FBA 履约费，零上传。', en: 'Estimate FBA fulfillment fee by marketplace & size tier, zero upload.' },
  titleLocTitle: { zh: '多语言标题优化器（本地）', en: 'Title Localizer (local)' },
  titleLocDesc: { zh: '内置词库给出同义/更本地化表达与密度提示，零上传。', en: 'Built-in synonym bank + density hints for listings, zero upload.' },
  kwTitle: { zh: '关键词密度分析（本地）', en: 'Keyword Density (local)' },
  kwDesc: { zh: '粘贴 Listing 分析词频与密度，零上传。', en: 'Analyze word frequency & density from your listing, zero upload.' },
  ccTitle: { zh: '字符计数器（本地）', en: 'Character Counter (local)' },
  ccDesc: { zh: '实时统计字符数并对照 Amazon / eBay 长度上限，零上传。', en: 'Live char count vs Amazon / eBay limits, zero upload.' },
  amazonTitle: { zh: 'Amazon 标题', en: 'Amazon title' },
  amazonDesc: { zh: 'Amazon 描述', en: 'Amazon desc' },
  ebayTitle: { zh: 'eBay 标题', en: 'eBay title' },
  tnTitle: { zh: '文本规范化（本地）', en: 'Text Normalizer (local)' },
  tnDesc: { zh: '批量去空格 / 去空行 / 去重 / 大小写 / 去非 ASCII，零上传。', en: 'Trim / drop blanks / dedupe / case / strip non-ASCII in batch, zero upload.' },
  qrTitle: { zh: '二维码生成 / 解码（本地）', en: 'QR Code Gen / Decode (local)' },
  qrDesc: { zh: '本地生成店铺/商品二维码、扫码解析，零上传。', en: 'Generate shop/product QR codes and scan-decode them, zero upload.' },
  urlCodecTitle: { zh: 'URL 编解码（本地）', en: 'URL Encode / Decode (local)' },
  urlCodecDesc: { zh: '调试回调/跟踪链接的 URL 编码与解码，零上传。', en: 'Encode/decode callback & tracking links for debugging, zero upload.' },
  htmlEntityTitle: { zh: 'HTML 实体编解码（本地）', en: 'HTML Entity Encode / Decode (local)' },
  htmlEntityDesc: { zh: '清理 Listing 富文本中的 HTML 实体，零上传。', en: 'Clean HTML entities from listing rich text, zero upload.' },
  tsTitle: { zh: '时间戳转换（本地）', en: 'Timestamp Converter (local)' },
  tsDesc: { zh: 'Unix 时间戳 ↔ 日期（多时区）互转，零上传。', en: 'Unix timestamp ↔ date (multi-timezone), zero upload.' },
  hashTitle: { zh: '哈希生成（本地）', en: 'Hash Generator (local)' },
  hashDesc: { zh: '本地 MD5/SHA 校验文件完整性，零上传。', en: 'Local MD5/SHA file-integrity checks, zero upload.' },
  barcodeTitle: { zh: '条形码生成（本地）', en: 'Barcode Generator (local)' },
  barcodeDesc: { zh: '本地生成 FNSKU/UPC 条码（贴标用），零上传。', en: 'Generate FNSKU/UPC barcodes for labeling, zero upload.' },
  exifTitle: { zh: 'EXIF 查看 / 清除（本地）', en: 'EXIF View / Strip (local)' },
  exifDesc: { zh: '查看并抹除图片 GPS/设备元数据，保护隐私，零上传。', en: 'View and erase image GPS/device metadata for privacy, zero upload.' },
  imgRenameTitle: { zh: '图片批量重命名（本地）', en: 'Batch Image Rename (local)' },
  imgRenameDesc: { zh: '按规则批量重命名产品图（如 SKU_001…），零上传。', en: 'Rename product images by rule (e.g. SKU_001…), zero upload.' },
  imgSizeTitle: { zh: '图片尺寸报表（本地）', en: 'Image Size Report (local)' },
  imgSizeDesc: { zh: '批量读取宽高/体积并生成 CSV 报表，零上传。', en: 'Read dimensions/size in batch and export a CSV report, zero upload.' },
  imgBorderTitle: { zh: '圆角 / 边框批处理（本地）', en: 'Rounded Corner / Border (local)' },
  imgBorderDesc: { zh: '主图统一圆角白边（平台要求），零上传。', en: 'Unify product main image rounded corners & white border, zero upload.' },
  dutyTitle: { zh: '关税估算（本地）', en: 'Duty Estimator (local)' },
  dutyDesc: { zh: '按 HS 编码 + 目的地国估算进口关税，零上传。', en: 'Estimate import duty by HS code + destination country, zero upload.' },
  returnCostTitle: { zh: '退货成本计算器（本地）', en: 'Return Cost Calculator (local)' },
  returnCostDesc: { zh: '按已售+退货率算真实净利，零上传。', en: 'Compute real net profit with sold + return rate, zero upload.' },
  multiProfitTitle: { zh: '多店铺利润对比（本地）', en: 'Multi-store Profit Compare (local)' },
  multiProfitDesc: { zh: '同屏对比多个 ASIN/SKU 利润，零上传。', en: 'Compare profit across multiple ASIN/SKU side by side, zero upload.' },
  titleAbTitle: { zh: '标题 A/B 对比（本地）', en: 'Title A/B Compare (local)' },
  titleAbDesc: { zh: '对比两版标题长度/关键词差异并高亮，零上传。', en: 'Highlight length/keyword diffs between two title versions, zero upload.' },
  bulletGenTitle: { zh: '五点描述生成器（本地）', en: 'Bullet Point Generator (local)' },
  bulletGenDesc: { zh: '按卖点模板批量产出 Bullet（本地词库），零上传。', en: 'Batch-produce bullets from a selling-point template (local bank), zero upload.' },
  sensitiveWordTitle: { zh: '敏感词检查（本地）', en: 'Sensitive Word Check (local)' },
  sensitiveWordDesc: { zh: '扫描 Listing 中的平台违禁词（本地词库），零上传。', en: 'Scan listings for platform prohibited words (local bank), zero upload.' },
  videoCompressTitle: { zh: '视频压缩（本地）', en: 'Video Compress (local)' },
  videoCompressDesc: { zh: '本地压缩视频体积、可选分辨率与码率，零上传，适合商品短视频。', en: 'Shrink video size locally with adjustable resolution & bitrate, zero upload — great for product clips.' },
  videoConvertTitle: { zh: '视频格式转换（本地）', en: 'Video Convert (local)' },
  videoConvertDesc: { zh: 'MP4 / WebM / MOV 本地互转，零上传。', en: 'Convert MP4 / WebM / MOV locally, zero upload.' },
  videoToGifTitle: { zh: '视频转 GIF（本地）', en: 'Video to GIF (local)' },
  videoToGifDesc: { zh: '截取片段转成 GIF 动图，零上传。', en: 'Turn a clip into an animated GIF, zero upload.' },
  videoTrimTitle: { zh: '视频裁剪（本地）', en: 'Video Trim (local)' },
  videoTrimDesc: { zh: '按起止时间裁剪视频片段，零上传。', en: 'Cut a video by start/end time, zero upload.' },
  videoMergeTitle: { zh: '视频合并（本地）', en: 'Video Merge (local)' },
  videoMergeDesc: { zh: '按顺序合并多个视频，零上传。', en: 'Merge several videos in order, zero upload.' },
  videoExtractAudioTitle: { zh: '视频提取音频（本地）', en: 'Extract Audio (local)' },
  videoExtractAudioDesc: { zh: '把视频中的音轨提取为 MP3，零上传。', en: 'Extract the audio track as MP3, zero upload.' },
  audioConvertTitle: { zh: '音频格式转换（本地）', en: 'Audio Convert (local)' },
  audioConvertDesc: { zh: 'MP3 / WAV / M4A 本地互转，零上传。', en: 'Convert MP3 / WAV / M4A locally, zero upload.' },
  audioTrimTitle: { zh: '音频裁剪（本地）', en: 'Audio Trim (local)' },
  audioTrimDesc: { zh: '按起止时间裁剪音频，零上传。', en: 'Trim audio by start/end time, zero upload.' },
  imagesToVideoTitle: { zh: '图片转视频（本地）', en: 'Images to Video (local)' },
  imagesToVideoDesc: { zh: '把多张图片合成带转场的视频，零上传。', en: 'Stitch images into a video with transitions, zero upload.' },
  videoFrameExtractTitle: { zh: '视频帧提取（本地）', en: 'Frame Extract (local)' },
  videoFrameExtractDesc: { zh: '按间隔抽取视频静帧，零上传。', en: 'Extract still frames at intervals, zero upload.' },
  videoResizeTitle: { zh: '视频分辨率调整（本地）', en: 'Video Resize (local)' },
  videoResizeDesc: { zh: '调整视频分辨率/比例，零上传。', en: 'Change video resolution / aspect ratio, zero upload.' },
  imagesToPdfTitle: { zh: '图片批量转 PDF（本地）', en: 'Images to PDF (local)' },
  imagesToPdfDesc: { zh: '把多张产品图合并为一个 PDF，零上传。', en: 'Combine multiple product images into one PDF, zero upload.' },
  csvCleanerTitle: { zh: 'CSV 清洗（本地）', en: 'CSV Cleaner (local)' },
  csvCleanerDesc: { zh: '去空行/去重/统一编码/拆分列，本地处理不上传。', en: 'Drop blanks / dedupe / normalize encoding / split columns, local, no upload.' },
  keywordFrequencyTitle: { zh: '词频统计（本地）', en: 'Keyword Frequency (local)' },
  keywordFrequencyDesc: { zh: '统计关键词出现频次与占比，零上传。', en: 'Count keyword occurrences & share, zero upload.' },
  priceCompareTitle: { zh: '竞品价格比对（本地）', en: 'Price Compare (local)' },
  priceCompareDesc: { zh: '粘贴多个 ASIN/价格批量比对，零上传。', en: 'Paste multiple ASINs/prices to compare in batch, zero upload.' },
  fxBulkTitle: { zh: '批量汇率换算（本地）', en: 'Bulk FX Convert (local)' },
  fxBulkDesc: { zh: '对整列金额按汇率表批量换算，零上传。', en: 'Convert a whole column of amounts by a rate table, zero upload.' },
  stockAlertTitle: { zh: '库存预警计算（本地）', en: 'Stock Alert (local)' },
  stockAlertDesc: { zh: '按销量与补货周期算安全库存，零上传。', en: 'Compute safety stock from sales & lead time, zero upload.' },
  profitReportTitle: { zh: '利润报表（本地）', en: 'Profit Report (local)' },
  profitReportDesc: { zh: '多 SKU 利润汇总与导出 CSV，零上传。', en: 'Summarize multi-SKU profit and export CSV, zero upload.' },
  reviewAnalyzerTitle: { zh: '评论分析（本地）', en: 'Review Analyzer (local)' },
  reviewAnalyzerDesc: { zh: '提取评论高频词与情感倾向，零上传。', en: 'Extract top words & sentiment from reviews, zero upload.' },
  volumetricWeightTitle: { zh: '体积重计算（本地）', en: 'Volumetric Weight (local)' },
  volumetricWeightDesc: { zh: '按长×宽×高算体积重与实重取大，零上传。', en: 'Compute volumetric vs actual weight (take the larger), zero upload.' },
  shippingEstimatorTitle: { zh: '物流费用估算（本地）', en: 'Shipping Estimator (local)' },
  shippingEstimatorDesc: { zh: '按重量/体积/目的地估运费，零上传。', en: 'Estimate shipping by weight / volume / destination, zero upload.' },
  dedupeTitle: { zh: '数据去重（本地）', en: 'Data Dedupe (local)' },
  dedupeDesc: { zh: '按主键列对表格去重，零上传。', en: 'Dedupe a table by a key column, zero upload.' },
  asinBatchTitle: { zh: 'ASIN 批量校验（本地）', en: 'ASIN Batch Check (local)' },
  asinBatchDesc: { zh: '批量校验 ASIN 格式与长度，零上传。', en: 'Validate ASIN format & length in batch, zero upload.' },
  pivotLiteTitle: { zh: '轻量数据透视（本地）', en: 'Pivot Lite (local)' },
  pivotLiteDesc: { zh: '按维度做计数/求和透视，零上传。', en: 'Count/sum by dimensions, zero upload.' },
  brandCheckTitle: { zh: '品牌名查重（本地）', en: 'Brand Name Check (local)' },
  brandCheckDesc: { zh: '检测自有品牌词是否撞名，零上传。', en: 'Check your brand name for collisions, zero upload.' },
  restrictedWordsTitle: { zh: '受限词库检测（本地）', en: 'Restricted Words (local)' },
  restrictedWordsDesc: { zh: '扫描文案中的平台受限/违禁词，零上传。', en: 'Scan copy for platform-restricted words, zero upload.' },
  glossaryTranslateTitle: { zh: '离线术语翻译（本地）', en: 'Glossary Translate (local)' },
  glossaryTranslateDesc: { zh: '用内置跨境词库做中英术语对照，零上传。', en: 'ZH/EN term lookup from a built-in cross-border glossary, zero upload.' },
  receiptOcrTitle: { zh: '票据 OCR 提取（本地）', en: 'Receipt OCR (local)' },
  receiptOcrDesc: { zh: '本地识别发票/收据关键信息，零上传。', en: 'Extract key fields from invoices/receipts locally, zero upload.' },
  watermarkBatchTitle: { zh: '批量水印图片（本地）', en: 'Batch Watermark (local)' },
  watermarkBatchDesc: { zh: '给一批图片叠加版权水印，零上传。', en: 'Stamp copyright watermark on a batch of images, zero upload.' },
  thumbnailGenTitle: { zh: '缩略图生成（本地）', en: 'Thumbnail Gen (local)' },
  thumbnailGenDesc: { zh: '批量生成统一尺寸缩略图，零上传。', en: 'Batch-generate uniform thumbnails, zero upload.' },
  imageCollageTitle: { zh: '图片拼接（本地）', en: 'Image Collage (local)' },
  imageCollageDesc: { zh: '把多张图拼成横/竖版海报，零上传。', en: 'Combine images into a row/column poster, zero upload.' },
  pdfEncryptTitle: { zh: 'PDF 加密（本地）', en: 'PDF Encrypt (local)' },
  pdfEncryptDesc: { zh: '给 PDF 设置打开密码，零上传。', en: 'Set an open password on a PDF, zero upload.' },
  pdfPageNumberTitle: { zh: 'PDF 加页码（本地）', en: 'PDF Page Number (local)' },
  pdfPageNumberDesc: { zh: '批量给 PDF 加页码，零上传。', en: 'Add page numbers to PDFs in batch, zero upload.' },
  diffTextTitle: { zh: '文本差异对比（本地）', en: 'Text Diff (local)' },
  diffTextDesc: { zh: '逐行对比两版文案差异，零上传。', en: 'Line-by-line diff between two copies of text, zero upload.' },
  regexTesterTitle: { zh: '正则测试器（本地）', en: 'Regex Tester (local)' },
  regexTesterDesc: { zh: '本地测试正则并高亮匹配，零上传。', en: 'Test regex and highlight matches locally, zero upload.' },
  uuidGeneratorTitle: { zh: 'UUID 生成（本地）', en: 'UUID Generator (local)' },
  uuidGeneratorDesc: { zh: '批量生成 UUID/SKU 编号，零上传。', en: 'Batch-generate UUIDs / SKU ids, zero upload.' },
  qrBatchTitle: { zh: '批量二维码生成（本地）', en: 'Batch QR (local)' },
  qrBatchDesc: { zh: '一次生成多个商品二维码，零上传。', en: 'Generate many product QR codes at once, zero upload.' },
  colorConvertTitle: { zh: '颜色格式转换（本地）', en: 'Color Convert (local)' },
  colorConvertDesc: { zh: 'HEX / RGB / HSL 互转，零上传。', en: 'Convert HEX / RGB / HSL, zero upload.' },
  markdownTableTitle: { zh: 'Markdown 转表格（本地）', en: 'Markdown Table (local)' },
  markdownTableDesc: { zh: '把 Markdown 表格转 CSV/HTML，零上传。', en: 'Convert a Markdown table to CSV/HTML, zero upload.' },
  listingTemplateTitle: { zh: 'Listing 模板生成（本地）', en: 'Listing Template (local)' },
  listingTemplateDesc: { zh: '按类目模板批量产出标题/要点，零上传。', en: 'Batch-produce titles/bullets from category templates, zero upload.' },
  keywordClusterTitle: { zh: '关键词聚类（本地）', en: 'Keyword Cluster (local)' },
  keywordClusterDesc: { zh: '按语义把关键词分组聚类，零上传。', en: 'Group keywords by semantics, zero upload.' },
  longTailGenTitle: { zh: '长尾词生成（本地）', en: 'Long-tail Gen (local)' },
  longTailGenDesc: { zh: '基于种子词扩展长尾词，零上传。', en: 'Expand seed words into long-tail keywords, zero upload.' },
  metaGenTitle: { zh: 'Meta 标签生成（本地）', en: 'Meta Tag Gen (local)' },
  metaGenDesc: { zh: '一键生成 title/description 标签，零上传。', en: 'Generate title/description tags in one click, zero upload.' },
  slugGenTitle: { zh: 'URL Slug 生成（本地）', en: 'URL Slug Gen (local)' },
  slugGenDesc: { zh: '把标题转成 SEO 友好的 URL slug，零上传。', en: 'Turn titles into SEO-friendly URL slugs, zero upload.' },
  titleTagTesterTitle: { zh: '标题标签测试（本地）', en: 'Title Tag Tester (local)' },
  titleTagTesterDesc: { zh: '预览标题在搜索结果的截断效果，零上传。', en: 'Preview title truncation in search results, zero upload.' },
  descGenTitle: { zh: '描述生成（本地）', en: 'Description Gen (local)' },
  descGenDesc: { zh: '按卖点模板批量产出描述，零上传。', en: 'Batch-produce descriptions from templates, zero upload.' },
  altTextGenTitle: { zh: 'Alt 文本生成（本地）', en: 'Alt Text Gen (local)' },
  altTextGenDesc: { zh: '为图片批量产出 SEO alt 文本，零上传。', en: 'Batch-produce SEO alt text for images, zero upload.' },
  keywordDensityTitle: { zh: '关键词密度（本地）', en: 'Keyword Density (local)' },
  keywordDensityDesc: { zh: '统计关键词在文案中的密度与位置，零上传。', en: 'Measure keyword density & placement, zero upload.' },
  lsiWordsTitle: { zh: 'LSI 关键词（本地）', en: 'LSI Keywords (local)' },
  lsiWordsDesc: { zh: '给出语义相关词建议，零上传。', en: 'Suggest semantically related terms, zero upload.' },
  questionMinerTitle: { zh: '问答挖掘（本地）', en: 'Question Miner (local)' },
  questionMinerDesc: { zh: '挖掘用户常问问题用于 FAQ，零上传。', en: 'Mine common questions for FAQs, zero upload.' },
  nicheFinderTitle: { zh: '利基发现（本地）', en: 'Niche Finder (local)' },
  nicheFinderDesc: { zh: '按热度/竞争粗略评估利基方向，零上传。', en: 'Roughly gauge niche demand vs competition, zero upload.' },
  competitorGapTitle: { zh: '竞品词差（本地）', en: 'Competitor Gap (local)' },
  competitorGapDesc: { zh: '对比竞品缺失的关键词，零上传。', en: 'Find keywords competitors miss, zero upload.' },
  contentOutlineTitle: { zh: '内容大纲（本地）', en: 'Content Outline (local)' },
  contentOutlineDesc: { zh: '按关键词结构产出文章大纲，零上传。', en: 'Build an article outline from keywords, zero upload.' },
  breadcrumbGenTitle: { zh: '面包屑生成（本地）', en: 'Breadcrumb Gen (local)' },
  breadcrumbGenDesc: { zh: '生成结构化面包屑，零上传。', en: 'Generate structured breadcrumbs, zero upload.' },
  hreflangCheckTitle: { zh: 'hreflang 检查（本地）', en: 'hreflang Check (local)' },
  hreflangCheckDesc: { zh: '校验多语言 hreflang 标注，零上传。', en: 'Validate multilingual hreflang tags, zero upload.' },
  sitemapValidateTitle: { zh: 'Sitemap 校验（本地）', en: 'Sitemap Validate (local)' },
  sitemapValidateDesc: { zh: '校验 sitemap 格式与链接，零上传。', en: 'Validate sitemap format & links, zero upload.' },
  robotsGenTitle: { zh: 'robots.txt 生成（本地）', en: 'robots.txt Gen (local)' },
  robotsGenDesc: { zh: '生成 robots 规则，零上传。', en: 'Generate robots rules, zero upload.' },
  serpPreviewTitle: { zh: 'SERP 预览（本地）', en: 'SERP Preview (local)' },
  serpPreviewDesc: { zh: '预览搜索结果样式的标题/描述，零上传。', en: 'Preview title/description as search results, zero upload.' },
  trendFinderTitle: { zh: '趋势发现（本地）', en: 'Trend Finder (local)' },
  trendFinderDesc: { zh: '粗略洞察品类趋势方向，零上传。', en: 'Roughly spot category trends, zero upload.' },
  rankTrackerTitle: { zh: '排名追踪（本地）', en: 'Rank Tracker (local)' },
  rankTrackerDesc: { zh: '记录并对比关键词排名变化，零上传。', en: 'Record & compare keyword rank changes, zero upload.' },
  batchRenameTitle: { zh: '批量重命名（本地）', en: 'Batch Rename (local)' },
  batchRenameDesc: { zh: '按规则批量重命名文件，零上传。', en: 'Rename files by rule in batch, zero upload.' },
  bulkImageResizeTitle: { zh: '批量图片缩放（本地）', en: 'Bulk Image Resize (local)' },
  bulkImageResizeDesc: { zh: '对一批图片统一缩放，零上传。', en: 'Resize a batch of images uniformly, zero upload.' },
  bulkConvertTitle: { zh: '批量格式转换（本地）', en: 'Bulk Convert (local)' },
  bulkConvertDesc: { zh: '对一批文件批量转格式，零上传。', en: 'Convert a batch of files in bulk, zero upload.' },
  csvMergeTitle: { zh: 'CSV 合并（本地）', en: 'CSV Merge (local)' },
  csvMergeDesc: { zh: '纵向/横向合并多个 CSV，零上传。', en: 'Merge multiple CSVs vertically/horizontally, zero upload.' },
  jsonToCsvTitle: { zh: 'JSON 转 CSV（本地）', en: 'JSON to CSV (local)' },
  jsonToCsvDesc: { zh: '把 JSON 数组导出为 CSV，零上传。', en: 'Export a JSON array to CSV, zero upload.' },
  csvToJsonTitle: { zh: 'CSV 转 JSON（本地）', en: 'CSV to JSON (local)' },
  csvToJsonDesc: { zh: '把 CSV 转为 JSON 数组，零上传。', en: 'Convert CSV into a JSON array, zero upload.' },
  xmlFormatTitle: { zh: 'XML 格式化（本地）', en: 'XML Format (local)' },
  xmlFormatDesc: { zh: '美化/压缩 XML，零上传。', en: 'Pretty-print or minify XML, zero upload.' },
  yamlConvertTitle: { zh: 'YAML 转换（本地）', en: 'YAML Convert (local)' },
  yamlConvertDesc: { zh: 'YAML 与 JSON 互转，零上传。', en: 'Convert YAML ↔ JSON, zero upload.' },
  envManagerTitle: { zh: '环境变量管理（本地）', en: 'Env Manager (local)' },
  envManagerDesc: { zh: '编辑/对比 .env 配置，零上传。', en: 'Edit/compare .env configs, zero upload.' },
  loremGenTitle: { zh: 'Lorem 文本（本地）', en: 'Lorem Gen (local)' },
  loremGenDesc: { zh: '生成占位文本，零上传。', en: 'Generate placeholder text, zero upload.' },
  cronTesterTitle: { zh: 'Cron 测试（本地）', en: 'Cron Tester (local)' },
  cronTesterDesc: { zh: '解析并预览 cron 表达式，零上传。', en: 'Parse & preview cron expressions, zero upload.' },
  mdPreviewTitle: { zh: 'Markdown 预览（本地）', en: 'Markdown Preview (local)' },
  mdPreviewDesc: { zh: '实时预览 Markdown 渲染，零上传。', en: 'Live Markdown render preview, zero upload.' },
  diffViewerTitle: { zh: 'Diff 查看（本地）', en: 'Diff Viewer (local)' },
  diffViewerDesc: { zh: '对比文件差异并高亮，零上传。', en: 'Highlight file diffs, zero upload.' },
  base64FileTitle: { zh: '文件 Base64（本地）', en: 'File Base64 (local)' },
  base64FileDesc: { zh: '把文件编码为 Base64，零上传。', en: 'Encode a file as Base64, zero upload.' },
  colorPaletteTitle: { zh: '调色板生成（本地）', en: 'Color Palette (local)' },
  colorPaletteDesc: { zh: '由主色生成配色方案，零上传。', en: 'Build a palette from a base color, zero upload.' },
  faviconGenTitle: { zh: 'Favicon 生成（本地）', en: 'Favicon Gen (local)' },
  faviconGenDesc: { zh: '由图片生成多尺寸 favicon，零上传。', en: 'Generate multi-size favicons from an image, zero upload.' },
  placeholderGenTitle: { zh: '占位图生成（本地）', en: 'Placeholder Gen (local)' },
  placeholderGenDesc: { zh: '生成指定尺寸占位图，零上传。', en: 'Generate sized placeholder images, zero upload.' },
  shortcutRefTitle: { zh: '快捷键速查（本地）', en: 'Shortcut Ref (local)' },
  shortcutRefDesc: { zh: '内置常用快捷键参考，零上传。', en: 'Built-in shortcut reference, zero upload.' },
  templateManagerTitle: { zh: '模板管理（本地）', en: 'Template Manager (local)' },
  templateManagerDesc: { zh: '保存/调用常用文案模板，零上传。', en: 'Save & reuse copy templates, zero upload.' },
  clipboardHistoryTitle: { zh: '剪贴板历史（本地）', en: 'Clipboard History (local)' },
  clipboardHistoryDesc: { zh: '记录本地剪贴板历史，零上传。', en: 'Keep a local clipboard history, zero upload.' },
  aboutDesc: { zh: 'CrossTool 是一个由独立开发者维护的跨境卖家本地隐私工具集合。所有工具 100% 在浏览器内运行，文件不上传服务器，断网也可用。', en: 'CrossTool is a local & private toolbox for cross-border sellers, maintained by an independent developer. Every tool runs 100% in your browser — files never leave your device and it works offline.' },
  aboutTechTitle: { zh: '技术栈', en: 'Tech stack' },
  aboutContactTitle: { zh: '联系方式', en: 'Contact' },
  coffeeTitle: { zh: '☕ 请作者喝杯咖啡', en: '☕ Buy me a coffee' },
  coffeeDesc: { zh: '如果 CrossTool 的工具对你有帮助，欢迎请作者喝杯咖啡，你的支持是持续维护的动力！', en: 'If CrossTool helps you, a coffee fuels continued maintenance — thank you!' },
};

export function ts(slug: string) {
  return { title: slug, desc: slug };
}